name: messagebird
version: 1.3.3
description: This repository provides a Dart client for MessageBird's REST API.
homepage: https://github.com/messagebird/dart-rest-api
repository: https://github.com/messagebird/dart-rest-api.git
documentation:
dependencies:
  http: ^0.12.0
  yaml: ^2.2.0
dev_dependencies:
  test: ^1.6.0
environment:
  sdk: '>=2.5.0 <3.0.0'
