name: messagebird_dart
description: This repository contains an unofficial Dart client for MessageBird's REST API
version: 0.2.0
homepage: https://git.dev.drillster.com/drillster/messagebird_dart
author: Luc van der Zandt <luc@drillster.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
