name: messagebird
version: 1.3.0
description: This repository provides a Dart client for MessageBird's REST API.
homepage: https://github.com/messagebird/dart-rest-api
repository: https://github.com/messagebird/dart-rest-api.git
documentation: 
dev_dependencies:
  test: ^1.6.0
environment:
  sdk: '>=2.5.0 <3.0.0'
