name: messagebird
version: 1.2.3
description: This repository provides an unofficial Dart client for MessageBird's REST API.
homepage: https://git.dev.drillster.com/drillster/messagebird-dart
repository: https://git.dev.drillster.com/drillster/messagebird-dart
documentation: 
dev_dependencies:
  test: ^1.6.0
environment:
  sdk: '>=2.5.0 <3.0.0'
